version: "3"
services:
  node_cont:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    command: node app.js
