version: "3"
services:
  node_cont:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: node-app
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-db:
